// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// cdtr.cpp
list cdt_triangulate_cpp(doubles x, doubles y, integers s0, integers s1, double max_area, double min_angle_deg, int max_steiner, double min_edge_length, bool conforming, int erase_mode, int intersect_mode, bool angle_first);
extern "C" SEXP _cdtr_cdt_triangulate_cpp(SEXP x, SEXP y, SEXP s0, SEXP s1, SEXP max_area, SEXP min_angle_deg, SEXP max_steiner, SEXP min_edge_length, SEXP conforming, SEXP erase_mode, SEXP intersect_mode, SEXP angle_first) {
  BEGIN_CPP11
    return cpp11::as_sexp(cdt_triangulate_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<integers>>(s0), cpp11::as_cpp<cpp11::decay_t<integers>>(s1), cpp11::as_cpp<cpp11::decay_t<double>>(max_area), cpp11::as_cpp<cpp11::decay_t<double>>(min_angle_deg), cpp11::as_cpp<cpp11::decay_t<int>>(max_steiner), cpp11::as_cpp<cpp11::decay_t<double>>(min_edge_length), cpp11::as_cpp<cpp11::decay_t<bool>>(conforming), cpp11::as_cpp<cpp11::decay_t<int>>(erase_mode), cpp11::as_cpp<cpp11::decay_t<int>>(intersect_mode), cpp11::as_cpp<cpp11::decay_t<bool>>(angle_first)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cdtr_cdt_triangulate_cpp", (DL_FUNC) &_cdtr_cdt_triangulate_cpp, 12},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cdtr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
