# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdt_triangulate_cpp <- function(x, y, s0, s1, max_area, min_angle_deg, max_steiner, min_edge_length, conforming, erase_mode, intersect_mode) {
    .Call(`_cdtr_cdt_triangulate_cpp`, x, y, s0, s1, max_area, min_angle_deg, max_steiner, min_edge_length, conforming, erase_mode, intersect_mode)
}

